package com.lanlink.shopping.mapper;

import org.apache.ibatis.annotations.*;
import java.util.*;

@Mapper
public interface TrafficMapper {
 @Select("SELECT COUNT(*) FROM t_product WHERE mer_id=#{merId} AND status=1 AND deleted=0") long countOnSale(@Param("merId")Long m);
 @Select("SELECT COALESCE(SUM(oi.subtotal),0) amount,COUNT(DISTINCT o.order_no) orders FROM t_order_item oi JOIN t_order o ON oi.order_no=o.order_no WHERE o.pay_status=1 AND o.pay_time>=DATE_SUB(NOW(),INTERVAL #{days} DAY) AND oi.prod_id IN(SELECT prod_id FROM t_product WHERE mer_id=#{merId} AND deleted=0)") Map<String,Object> sumRecent(@Param("merId")Long m,@Param("days")int d);
 @Select("SELECT COALESCE(SUM(oi.subtotal),0) amount,COALESCE(SUM(oi.quantity),0) sold FROM t_order_item oi JOIN t_order o ON oi.order_no=o.order_no WHERE o.pay_status=1 AND oi.prod_id IN(SELECT prod_id FROM t_product WHERE mer_id=#{merId} AND deleted=0)") Map<String,Object> sumTotal(@Param("merId")Long m);
 @Select("SELECT COALESCE(SUM(oi.subtotal),0) amount,COUNT(DISTINCT o.order_no) orders FROM t_order_item oi JOIN t_order o ON oi.order_no=o.order_no WHERE o.pay_status=1 AND o.pay_time>=DATE_SUB(NOW(),INTERVAL #{times2} DAY) AND o.pay_time<DATE_SUB(NOW(),INTERVAL #{days} DAY) AND oi.prod_id IN(SELECT prod_id FROM t_product WHERE mer_id=#{merId} AND deleted=0)") Map<String,Object> sumPrevPeriod(@Param("merId")Long m,@Param("days")int d,@Param("times2")int d2);
 @Select("SELECT COALESCE(o.pay_channel,'unknown') channel,COUNT(DISTINCT o.order_no) orders,COALESCE(SUM(oi.subtotal),0) amount FROM t_order_item oi JOIN t_order o ON oi.order_no=o.order_no WHERE o.pay_status=1 AND o.pay_time>=DATE_SUB(NOW(),INTERVAL #{days} DAY) AND oi.prod_id IN(SELECT prod_id FROM t_product WHERE mer_id=#{merId} AND deleted=0) GROUP BY COALESCE(o.pay_channel,'unknown') ORDER BY amount DESC") List<Map<String,Object>> channelStats(@Param("merId")Long m,@Param("days")int d);
 @Select("SELECT COUNT(DISTINCT oi.prod_id) FROM t_order_item oi JOIN t_order o ON oi.order_no=o.order_no WHERE o.pay_status=1 AND oi.prod_id IN(SELECT prod_id FROM t_product WHERE mer_id=#{merId} AND deleted=0)") long countActiveProducts(@Param("merId")Long m);
 @Select("SELECT DATE_FORMAT(o.pay_time,'%Y-%m-%d') date,SUM(oi.subtotal) amount,COUNT(DISTINCT o.order_no) orders FROM t_order_item oi JOIN t_order o ON oi.order_no=o.order_no WHERE o.pay_status=1 AND o.pay_time>=DATE_SUB(NOW(),INTERVAL #{days} DAY) AND oi.prod_id IN(SELECT prod_id FROM t_product WHERE mer_id=#{merId} AND deleted=0) GROUP BY DATE_FORMAT(o.pay_time,'%Y-%m-%d') ORDER BY date") List<Map<String,Object>> trendByDay(@Param("merId")Long m,@Param("days")int d);
 @Select("SELECT p.prod_id prodId,p.title,p.cover_url coverUrl,p.price,p.stock,COALESCE(SUM(CASE WHEN o.pay_status=1 AND o.pay_time>=DATE_SUB(NOW(),INTERVAL #{days} DAY) THEN oi.quantity END),0) sold,COALESCE(SUM(CASE WHEN o.pay_status=1 AND o.pay_time>=DATE_SUB(NOW(),INTERVAL #{days} DAY) THEN oi.subtotal END),0) amount FROM t_product p LEFT JOIN t_order_item oi ON oi.prod_id=p.prod_id LEFT JOIN t_order o ON oi.order_no=o.order_no WHERE p.mer_id=#{merId} AND p.deleted=0 GROUP BY p.prod_id,p.title,p.cover_url,p.price,p.stock ORDER BY amount DESC,sold DESC") List<Map<String,Object>> productRanking(@Param("merId")Long m,@Param("days")int d);
 @Select("SELECT COALESCE(e.source_type,'unknown') source,COUNT(*) events,COUNT(DISTINCT e.session_id) uv,SUM(e.event_type='VIEW_PRODUCT') productViews,SUM(e.event_type='ADD_CART') carts,SUM(e.event_type='PAY') pays FROM t_traffic_event e WHERE e.merchant_id=#{merId} AND e.event_time>=DATE_SUB(NOW(),INTERVAL #{days} DAY) GROUP BY COALESCE(e.source_type,'unknown') ORDER BY uv DESC") List<Map<String,Object>> sourceStats(@Param("merId")Long m,@Param("days")int d);
 @Select("SELECT COUNT(DISTINCT CASE WHEN event_type='VISIT' THEN session_id END) visits,COUNT(DISTINCT CASE WHEN event_type='VIEW_PRODUCT' THEN session_id END) views,COUNT(DISTINCT CASE WHEN event_type='ADD_CART' THEN session_id END) carts,COUNT(DISTINCT CASE WHEN event_type='PAY' THEN session_id END) pays FROM t_traffic_event WHERE merchant_id=#{merId} AND event_time>=DATE_SUB(NOW(),INTERVAL #{days} DAY)") Map<String,Object> funnel(@Param("merId")Long m,@Param("days")int d);
 @Select("SELECT p.prod_id prodId,p.title,COUNT(DISTINCT CASE WHEN e.event_type='VIEW_PRODUCT' THEN e.session_id END) views,COUNT(DISTINCT CASE WHEN e.event_type='ADD_CART' THEN e.session_id END) carts,COUNT(DISTINCT CASE WHEN e.event_type='PAY' THEN e.session_id END) pays FROM t_product p LEFT JOIN t_traffic_event e ON e.product_id=p.prod_id AND e.event_time>=DATE_SUB(NOW(),INTERVAL #{days} DAY) WHERE p.mer_id=#{merId} AND p.deleted=0 GROUP BY p.prod_id,p.title HAVING views>0 ORDER BY views DESC LIMIT 20") List<Map<String,Object>> productFunnel(@Param("merId")Long m,@Param("days")int d);
 @Insert("INSERT INTO t_traffic_event(merchant_id,product_id,user_id,session_id,event_type,source_type,source_detail,page_url,device_type,event_time) VALUES(#{merchantId},#{productId},#{userId},#{sessionId},#{eventType},#{sourceType},#{sourceDetail},#{pageUrl},#{deviceType},NOW())") int insertEvent(Map<String,Object> e);
}