import { createRouter, createWebHistory } from 'vue-router'
import MainLayout from '../layouts/MainLayout.vue'
function readUser(){try{return JSON.parse(localStorage.getItem('ll_user')||'null')}catch(e){return null}}
function hasPerms(user,perms){if(!perms||!perms.length)return true;const owned=(user&&user.identity&&user.identity.permissions)||[];return perms.every(p=>owned.includes(p))}
const routes=[{path:'/',component:MainLayout,children:[
{path:'',name:'home',component:()=>import('../views/Home.vue')},{path:'mall',name:'mall',component:()=>import('../views/Mall.vue')},{path:'promotions',name:'promotions',component:()=>import('../views/PromotionCenter.vue')},{path:'promotions/:id',name:'promotion-detail',component:()=>import('../views/PromotionDetail.vue')},{path:'product/:id',name:'product',component:()=>import('../views/ProductDetail.vue')},
{path:'cart',name:'cart',component:()=>import('../views/Cart.vue'),meta:{auth:true,perms:['cart:manage']}},{path:'checkout',name:'checkout',component:()=>import('../views/Checkout.vue'),meta:{auth:true,perms:['order:create']}},{path:'orders',name:'orders',component:()=>import('../views/MyOrders.vue'),meta:{auth:true,perms:['order:view']}},{path:'orders/:orderNo',name:'order-detail',component:()=>import('../views/OrderDetail.vue'),meta:{auth:true,perms:['order:view']}},
{path:'wallet',name:'wallet',component:()=>import('../views/Wallet.vue'),meta:{auth:true}},{path:'credit-term',name:'credit-term',component:()=>import('../views/CreditTermCenter.vue'),meta:{auth:true,perms:['credit:view']}},{path:'credit-term/apply',name:'credit-term-apply',component:()=>import('../views/CreditTermApply.vue'),meta:{auth:true,perms:['credit:apply']}},{path:'credit-term/bills',name:'credit-term-bills',component:()=>import('../views/CreditTermBills.vue'),meta:{auth:true,perms:['credit:view']}},{path:'credit-term/bills/:id',name:'credit-term-bill-detail',component:()=>import('../views/CreditTermBillDetail.vue'),meta:{auth:true,perms:['credit:view']}},{path:'wallet/transactions',name:'wallet-transactions',component:()=>import('../views/WalletTransactions.vue'),meta:{auth:true}},{path:'wallet/transactions/:id',name:'wallet-transaction-detail',component:()=>import('../views/WalletTransactionDetail.vue'),meta:{auth:true}},{path:'wallet/recharge',name:'wallet-recharge',component:()=>import('../views/WalletRecharge.vue'),meta:{auth:true}},{path:'wallet/recharge/result/:id',name:'wallet-recharge-result',component:()=>import('../views/WalletRechargeResult.vue'),meta:{auth:true}},
{path:'merchant',name:'merchant',component:()=>import('../views/MerchantApply.vue'),meta:{auth:true}},{path:'merchant/products',name:'merchant-products',component:()=>import('../views/MerchantProducts.vue'),meta:{auth:true,perms:['product:publish']}},{path:'merchant/traffic',name:'merchant-traffic',component:()=>import('../views/MerchantTraffic.vue'),meta:{auth:true,perms:['merchant:manage']}},
{path:'activity',name:'activity',component:()=>import('../views/ActivityCenter.vue'),meta:{auth:true}},{path:'activity/:id',name:'activity-detail',component:()=>import('../views/ActivityDetail.vue'),meta:{auth:true}},{path:'activity/:id/participation',name:'activity-participation',component:()=>import('../views/ActivityParticipationResult.vue'),meta:{auth:true}},{path:'activity/my',name:'activity-my',component:()=>import('../views/ActivityMy.vue'),meta:{auth:true}},{path:'activity/rules',name:'activity-rules',component:()=>import('../views/ActivityRules.vue'),meta:{auth:true}},
{path:'membership',name:'membership',component:()=>import('../views/MembershipCenter.vue'),meta:{auth:true}},{path:'membership/levels',name:'membership-levels',component:()=>import('../views/MembershipLevels.vue'),meta:{auth:true}},{path:'membership/points',name:'membership-points',component:()=>import('../views/MembershipPoints.vue'),meta:{auth:true}},{path:'membership/points/:id',name:'membership-point-detail',component:()=>import('../views/MembershipPointDetail.vue'),meta:{auth:true}},{path:'membership/benefits',name:'membership-benefits',component:()=>import('../views/MembershipBenefits.vue'),meta:{auth:true}},
{path:'about',name:'about',component:()=>import('../views/AboutUs.vue')},{path:'me',name:'me',component:()=>import('../views/Me.vue'),meta:{auth:true,perms:['profile:manage']}},{path:'me/messages',name:'account-messages',component:()=>import('../views/AccountMessages.vue'),meta:{auth:true,perms:['profile:manage']}},{path:'me/address',name:'account-addresses',component:()=>import('../views/AccountAddresses.vue'),meta:{auth:true,perms:['profile:manage']}},{path:'me/login-log',name:'account-login-log',component:()=>import('../views/AccountLoginLog.vue'),meta:{auth:true,perms:['profile:manage']}},{path:'me/settings',name:'account-settings',component:()=>import('../views/AccountSettings.vue'),meta:{auth:true,perms:['profile:manage']}}
]},{path:'/login',name:'login',component:()=>import('../views/Login.vue')},{path:'/register',name:'register',component:()=>import('../views/Register.vue')},{path:'/admin',component:()=>import('../layouts/AdminLayout.vue'),meta:{admin:true},children:[{path:'',name:'admin-home',redirect:{name:'admin-dash'}},{path:'dashboard',name:'admin-dash',component:()=>import('../views/admin/AdminDashboard.vue')},{path:'merchants',name:'admin-merchants',component:()=>import('../views/admin/MerchantReview.vue')},{path:'merchants/:merId',name:'admin-merchant-detail',component:()=>import('../views/admin/MerchantDetail.vue')},{path:'products',name:'admin-products',component:()=>import('../views/admin/AdminProducts.vue')},{path:'payments',name:'admin-payments',component:()=>import('../views/admin/AdminPayments.vue')},{path:'credit-terms',name:'admin-credit-terms',component:()=>import('../views/admin/AdminCreditTerms.vue')},{path:'payments/:orderNo',name:'admin-payment-detail',component:()=>import('../views/admin/PaymentDetail.vue')},{path:'audit',name:'admin-audit',component:()=>import('../views/admin/AdminAuditLog.vue')}]}]
const router=createRouter({history:createWebHistory(),routes})
router.beforeEach(to=>{const user=readUser();if(to.meta.admin){if(!user||user.roleCode!=='admin')return{name:'home'};return true}if(to.meta.auth&&!user)return{name:'login',query:{redirect:to.fullPath}};if(to.meta.perms&&user&&!hasPerms(user,to.meta.perms))return{name:'home'};return true})
export default router