<template><div class="sys">
  <div class="hero"><div><div class="eyebrow">LANLINK MEMBERSHIP</div><h1>会员中心</h1><p>围绕等级、成长、积分与权益建立完整会员闭环。</p></div><div class="actions"><a-button type="primary" @click="$router.push('/membership/points')">积分中心</a-button><a-button @click="$router.push('/membership/benefits')">我的权益</a-button></div></div>
  <a-card v-if="data" :bordered="false" class="member"><div><div class="level">{{data.level?.levelName||'普通会员'}}</div><div class="meta">成长值 {{data.card?.growth||0}} · 积分 {{data.card?.points||0}}</div></div><div class="discount">{{rate}}<small>等级折扣</small></div><div class="progress"><div :style="{width:growthPct}"></div></div><span class="hint">{{nextHint}}</span></a-card>
  <div class="grid"><a-card v-for="x in cards" :key="x.title" :bordered="false" class="nav-card" @click="$router.push(x.to)"><div class="num">{{x.num}}</div><h3>{{x.title}}</h3><p>{{x.desc}}</p><span>进入 →</span></a-card></div>
  <a-card :bordered="false" class="levels" title="等级速览"><a-steps :current="currentIndex" responsive size="small"><a-step v-for="l in (data?.levels||[])" :key="l.levelId" :title="l.levelName" :description="l.minGrowth+' 成长值'"/></a-steps></a-card>
</div></template>
<script setup>
import {ref,computed,onMounted} from 'vue';import {membershipApi} from '../api'
const data=ref(null);const cards=[{num:'01',title:'等级权益',desc:'成长值门槛、等级折扣与体系说明',to:'/membership/levels'},{num:'02',title:'积分中心',desc:'积分余额、获取、抵现与流水',to:'/membership/points'},{num:'03',title:'会员权益',desc:'折扣、积分、成长值等权益说明',to:'/membership/benefits'}];const rate=computed(()=>{const r=Number(data.value?.level?.discountRate||1);return r>=1?'无折扣':(r*10).toFixed(1)+' 折'});const currentIndex=computed(()=>Math.max(0,(data.value?.levels||[]).findIndex(x=>x.levelId===data.value?.level?.levelId)));const growthPct=computed(()=>{const ls=data.value?.levels||[],cur=data.value?.level?.minGrowth||0,n=ls.find(x=>x.minGrowth>cur);if(!n)return '100%';const got=(data.value?.card?.growth||0)-cur;return Math.max(5,Math.min(100,got/(n.minGrowth-cur)*100))+'%'});const nextHint=computed(()=>{const ls=data.value?.levels||[],cur=data.value?.level?.minGrowth||0,n=ls.find(x=>x.minGrowth>cur);return n?'距离 '+n.levelName+' 还需成长值 '+Math.max(0,n.minGrowth-(data.value?.card?.growth||0)):'已达最高等级'});onMounted(async()=>{try{data.value=await membershipApi.my()}catch(e){}})</script>
<style scoped>
.sys{max-width:1040px;margin:0 auto}.hero{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:20px}.eyebrow{font-size:11px;letter-spacing:.18em;color:var(--ll-primary)}h1{margin:5px 0;font-size:30px}.hero p{margin:0;color:var(--ll-muted)}.actions{display:flex;gap:8px}.member{border-radius:22px;background:var(--ll-brand-hero-gradient);color:#fff;margin-bottom:16px;position:relative;overflow:hidden}.level{font-size:28px;font-weight:800}.meta,.hint{opacity:.72}.discount{position:absolute;right:26px;top:24px;text-align:right;font-size:24px;font-weight:800}.discount small{display:block;font-size:11px;font-weight:400;opacity:.65}.progress{height:6px;border-radius:99px;background:rgba(255,255,255,.14);margin:22px 0 8px;overflow:hidden}.progress div{height:100%;background:#f6d38a;border-radius:99px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:16px}.nav-card,.levels{border-radius:18px}.nav-card{cursor:pointer;transition:transform .2s,box-shadow .2s}.nav-card:hover{transform:translateY(-3px);box-shadow:0 16px 40px rgba(19,35,58,.08)}.num{font-size:11px;color:#9b2d20;letter-spacing:.14em}.nav-card h3{margin:8px 0 4px}.nav-card p{color:var(--ll-muted);font-size:12px}.nav-card span{color:var(--ll-primary);font-size:12px}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.hero{flex-direction:column}.grid{grid-template-columns:1fr}.discount{position:static;text-align:left;margin-top:12px}}
</style>