<template><div class="sys">
  <div class="hero"><div><div class="eyebrow">LANLINK WALLET</div><h1>我的钱包</h1><p>统一管理余额、充值与资金流水。</p></div><div class="hero-actions"><a-button type="primary" size="large" @click="$router.push('/wallet/recharge')">充值</a-button><a-button ghost size="large" @click="$router.push('/wallet/transactions')">全部流水</a-button></div></div>
  <div class="balance"><div><span>可用余额</span><strong>¥{{balanceText}}</strong><small>钱包支付实时到账 · 退款按钱包渠道入账</small></div><div class="quick"><a-button @click="$router.push('/wallet/recharge')">充值</a-button><a-button @click="$router.push('/orders')">去支付订单</a-button></div></div>
  <div class="grid"><a-card v-for="x in cards" :key="x.title" :bordered="false" class="nav-card" @click="$router.push(x.to)"><div class="num">{{x.num}}</div><h3>{{x.title}}</h3><p>{{x.desc}}</p><span>进入 →</span></a-card></div>
  <a-card :bordered="false" class="logs" title="最近流水"><a-list :data-source="logs.slice(0,6)"><template #renderItem="{item}"><a-list-item><div><a-tag :color="colors[item.changeType]||'default'">{{labels[item.changeType]||item.changeType}}</a-tag>{{item.remark||''}}<div class="time">{{String(item.createTime||'').replace('T',' ')}}</div></div><b :class="Number(item.amount)>=0?'plus':'minus'">{{Number(item.amount)>=0?'+':''}}¥{{Number(item.amount||0).toFixed(2)}}</b></a-list-item></template></a-list><a-empty v-if="!logs.length" description="暂无流水"/><template #actions><a-button type="link" @click="$router.push('/wallet/transactions')">查看全部流水</a-button></template></a-card>
</div></template>
<script setup>
import {ref,computed,onMounted} from 'vue';import {walletApi} from '../api'
const balance=ref(0),logs=ref([]),balanceText=computed(()=>Number(balance.value||0).toFixed(2));const labels={recharge:'充值',pay:'消费',refund:'退款入账'},colors={recharge:'blue',pay:'orange',refund:'green'};const cards=[{num:'01',title:'钱包流水',desc:'收入、支出、退款与订单关联记录',to:'/wallet/transactions'},{num:'02',title:'充值中心',desc:'选择金额并完成钱包充值',to:'/wallet/recharge'},{num:'03',title:'支付订单',desc:'查看待支付订单并使用钱包',to:'/orders'}];onMounted(async()=>{try{const d=await walletApi.my();balance.value=d?.balance||0;logs.value=d?.logs||[]}catch(e){}})
</script>
<style scoped>
.sys{max-width:1040px;margin:0 auto}.hero{display:flex;justify-content:space-between;gap:24px;align-items:center;margin-bottom:18px}.eyebrow{font-size:11px;letter-spacing:.18em;color:var(--ll-primary)}h1{margin:5px 0;font-size:30px}.hero p{margin:0;color:var(--ll-muted)}.hero-actions{display:flex;gap:10px}.balance{padding:26px;border-radius:22px;background:var(--ll-brand-hero-gradient);color:#fff;display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:16px;box-shadow:var(--ll-glass-shadow)}.balance span,.balance small{display:block;opacity:.7}.balance strong{display:block;font-size:42px;margin:4px 0}.quick{display:flex;gap:8px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:16px}.nav-card,.logs{border-radius:18px}.nav-card{cursor:pointer;transition:transform .2s,box-shadow .2s}.nav-card:hover{transform:translateY(-3px);box-shadow:0 16px 40px rgba(19,35,58,.08)}.num{font-size:11px;color:#9b2d20;letter-spacing:.14em}.nav-card h3{margin:8px 0 4px}.nav-card p,.time{color:var(--ll-muted);font-size:12px}.nav-card span{color:var(--ll-primary);font-size:12px}.plus{color:#16835a}.minus{color:#9b2d20}@media(max-width:700px){.hero,.balance{align-items:flex-start;flex-direction:column}.grid{grid-template-columns:1fr 1fr}}@media(max-width:480px){.grid{grid-template-columns:1fr}.balance strong{font-size:34px}}
</style>